### ISSUE TITLE
Example code crashes on OpenBSD

### ISSUE THREAD

**Issue by vext01** [jeaye/ncurses-rs#120]
Hi,

The "move a window" example (https://github.com/jeaye/ncurses-rs/blob/master/examples/ex_4.rs) crashes on OpenBSD on rust rust-1.13.0.

The line which causes the crash is:
```
printw("Use the arrow keys to move");
```

Using gdb, it seems that something is smashing the stack:

```
Program received signal SIGABRT, Aborted.
0x0000113593013b9a in thrkill () at <stdin>:2
2       <stdin>: No such file or directory.
        in <stdin>
Current language:  auto; currently asm
(gdb) bt
#0  0x0000113593013b9a in thrkill () at <stdin>:2
#1  0x000011359305906f in *_libc___stack_smash_handler (func=0x1134a8d41d1a "wprintw", damaged=Variable "damaged" is not available.
)
    at /usr/src/lib/libc/sys/stack_protector.c:79
#2  0x00001134a8c1dc68 in wprintw (win=Variable "win" is not available.
) at /usr/src/lib/libcurses/base/lib_printw.c:84
#3  0x000011329b201fd6 in ?? () from /home/edd/source/fj/target/debug/fj
#4  0x0000000000000000 in ?? ()
```

(Note, I'm very new to rust and don't really know what I'm doing ;) )

**Comment by hectorgrey** [comment]
That's certainly odd - I don't have an OpenBSD machine to test that on; all I know is that the example works fine on Arch Linux (which is clearly not very useful).  Hopefully someone a bit more knowledgeable can be of some use?

**Comment by gyscos** [comment]
What is the version of ncurses installed?
As seen in #119, at least Ubuntu ships ncurses 5, which uses different sizes for some types, and could lead to stack corruption.

**Comment by vext01** [comment]
OpenBSD has ncurses-5.7 in base:
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libcurses/

**Comment by hectorgrey** [comment]
Ah, OK.  The latest version of ncurses is 6.0 - if you can update to that and try again, it would be worth seeing if that fixes the problem.
